### ISSUE TITLE
Optional augmentation for custom_unet?

### ISSUE THREAD

**Issue by EtagiBI** [karolzak/keras-unet#17]
Hello,

Is it possible to add augmentation as optional parameter in custom unet model? In my case augmentation does more harm than good.

**Comment by karolzak** [comment]
Hi @EtagiBI , 
Could you elaborate a bit? What do you mean by:
>  ..add augmentation as optional parameter in custom unet model

There's no data augmentation happening inside the model itself. However if you're talking about the example in notebooks then you are free to modify it for your needs. Data augmentation usually helps to prevent overfitting but you always have to adjust types of transformations you're using and check if they make sense for your type of data

**Comment by karolzak** [comment]
closing due to lack of response

**Comment by EtagiBI** [comment]
Hi @karolzak 
Pardon me, email notification lost in spam.
My question was about `get_augmented` function in `utils.py`. As far as I understand, `data_gen_args` is an essential set of parameters for this function. Should I set all augumentation options within `data_gen_args` to 0 / False to avoid any augumentation?

**Comment by karolzak** [comment]
Hi @EtagiBI 
data_gen_args param should be a dictionary of key-value pairs where key is one of the Keras ImageDataGenerator arguments and value is the value you want to set it to. If you don't want to use any augmentation there you should just asign an empty dictionary to data_gen_args. 

I honestly think this should be handled differently but that's how it was rapidly developed at the time and I just never changed it.

The full list of available param names and values for this function can be found here:
https://keras.io/api/preprocessing/image/ under ImageDataGenerator class

Hope this helps!
