### ISSUE TITLE
Proper mask shape for a multiclass task

### ISSUE THREAD

**Issue by EtagiBI** [karolzak/keras-unet#25]
Hello,

I'm trying to use `custom_unet` for a multiclass task. In my case all masks inputs have a following shape 
(BATCH_SIZE, NUMBER_OF_CLASSES, IMAGE_WIDTH, IMAGE_HEIGHT, 1).
Since I have 4 different colours on the black background and my images're 256x256 pixels and I use batch size of 4, I end up with the following shape:
(4, 4, 256, 256, 1).
Unfortunately, `custom_unet` doesn't like this shape giving me this error:

```
<...>
  File "C:\Users\E-soft\Anaconda3\envs\Explorium\lib\site-packages\keras_unet\losses.py", line 44, in jaccard_distance
    intersection = K.sum(K.abs(y_true * y_pred), axis=-1)
  File "C:\Users\E-soft\Anaconda3\envs\Explorium\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 899, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\E-soft\Anaconda3\envs\Explorium\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 1206, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\Users\E-soft\Anaconda3\envs\Explorium\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 6698, in mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4,4,256,256] vs. [4,256,256,4] [Op:Mul] name: loss/conv2d_18_loss/mul/
```
It seems that I should reshape my input for masks, Should it be 
(BATCH_SIZE IMAGE_WIDTH, IMAGE_HEIGHT, NUMBER_OF_CLASSES, 1)?

**Comment by karolzak** [comment]
Hi @EtagiBI !

For multiclass semantic segmentation tasks you need to reshape your masks into `(BATCH_SIZE IMAGE_WIDTH, IMAGE_HEIGHT, NUMBER_OF_CLASSES)`.   
And to explain why behind it: with this shape you should treat `NUMBER_OF_CLASSES` as a number of layers in your output masks where each layer represents each class you are trying to predict. In other words your output mask will be a volume of binary masks where each mask represents predictions for specific class.

To give you some visuals on a dummy example:
```python
print(x.shape, y.shape, y_pred.shape)
(1, 256, 256, 3) (1, 256, 256, 3) (1, 256, 256, 3)

utils.plot_imgs(
    org_imgs=np.vstack(
        (x, x, x)),
    mask_imgs=np.stack(
        (y[0][:,:,0],  # first layer of mask is the first class gt
         y[0][:,:,1],   # second layer of mask is the second class gt
         y[0][:,:,2])),   # third layer of mask is the third class gt
    pred_imgs=np.stack(
        (y_pred[0][:,:,0],  # first layer of mask is the first class predictions
         y_pred[0][:,:,1],   # second layer of mask is the second class predictions
         y_pred[0][:,:,2]))   # third layer of mask is the third class predictions
)
```

![image](https://user-images.githubusercontent.com/9843623/85994856-a89b4f00-b9f8-11ea-96c7-7f9fc3731255.png)

**Comment by EtagiBI** [comment]
Thanks for your reply!

Here's one of my masks:
![sample](https://user-images.githubusercontent.com/20855725/86130064-0dd86880-bafd-11ea-8913-27b4cd933de2.jpg)

I use a following code to create an encoded array for learning:
```
COLOR_PACK = (60, 30, 16, 120)
masks = np.zeros((4, 512, 512)).astype('float')
image_hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
for i, color in enumerate(COLOR_PACK):
    hsv_min = np.asarray([color - 5, 100, 100])
    hsv_max = np.asarray([color + 5, 255, 255])
    mask = cv2.inRange(image_hsv, hsv_min, hsv_max) / 255.
    masks[i] = mask
masks_pack = masks.swapaxes(0, -1) # The result of this operation is an array of shape (512, 512, 4)
```
Is it a valid way to encode multicoloк masks?

**Comment by karolzak** [comment]
@EtagiBI 
I quickly checked your code and I don't think it's correct:
- `swapaxes` is rotating your output image (I advise to always visualize outputs with matplotlib or something to verify if everything is ok)
- `COLOR_PACK` values seems to be a bit inaccurate (at least in my experiment it didn't pick up red color

Code below works for me (notice inline comments):

```python
import cv2

image = cv2.imread("../../dumpster/multiclass_segm.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # converting to RGB to plot with actual colors in matplotlib

COLOR_PACK = (60, 30, 5, 120)  # notice I changed the third value here (it was not picking up red color with previous setup)
masks = np.zeros((512, 512, 4)).astype('float')  # we go straight with to the target shape and use slicing
image_hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)  # changed conversion to RGB2HSV
for i, color in enumerate(COLOR_PACK):
    hsv_min = np.asarray([color - 5, 100, 100])
    hsv_max = np.asarray([color + 5, 255, 255])
    mask = cv2.inRange(image_hsv, hsv_min, hsv_max) / 255.
    masks[:,:,i] = mask  # using slicing to assign correct values to correct layers
# no need to swap axes anymore
# masks_pack = masks.swapaxes(0, -1) # The result of this operation is an array of shape (512, 512, 4) 
```

```python
import matplotlib.pyplot as plt

for i, color in enumerate(['green', 'yellow', 'red', 'blue']):
    plt.imshow(masks[:,:,i])
    plt.title(color)
    plt.show()
```
green             |  yellow | red | blue
:-------------------------:|:-------------------------:|:---------------:|:-----------:
![image](https://user-images.githubusercontent.com/9843623/86133989-5c7c0780-bae9-11ea-8a22-5b981e4f863b.png) | ![image](https://user-images.githubusercontent.com/9843623/86134131-87fef200-bae9-11ea-980d-d46ab92892d8.png) | ![image](https://user-images.githubusercontent.com/9843623/86134168-95b47780-bae9-11ea-9772-4f3a2600989f.png) | ![image](https://user-images.githubusercontent.com/9843623/86134183-9b11c200-bae9-11ea-933d-83921896f866.png)


Or:
```python
from keras_unet import utils

utils.plot_imgs(
    org_imgs=np.stack(
        (image, image, image, image)),
    mask_imgs=np.stack(
        (masks[:,:,0],
         masks[:,:,1], 
         masks[:,:,2], 
         masks[:,:,3])), 
    nm_img_to_plot=4,
    figsize=10
)
```
![image](https://user-images.githubusercontent.com/9843623/86136413-5d626880-baec-11ea-8cad-7ae01fbf79b3.png)

**Comment by EtagiBI** [comment]
Thank you!

Axes manupulations still confuse me a lot... What other changes should be done in `custom_unet` for a multiclass task? I assume that softmax is more appropriate output activation function. Anything else?

**Comment by karolzak** [comment]
@EtagiBI no problem.  
I honestly haven't used U-NETs for multiclass (in case of multiple classes I just trained multiple single class models) so not much to advise here other than `custom_unet` offers variety of different hyperparameters to play with so it makes sense to experiment with different settings and check what works best for your problem space.

**Comment by EtagiBI** [comment]
> 
> 
> @EtagiBI no problem.
> I honestly haven't used U-NETs for multiclass (in case of multiple classes I just trained multiple single class models) so not much to advise here other than `custom_unet` offers variety of different hyperparameters to play with so it makes sense to experiment with different settings and check what works best for your problem space.

Oh, I see. That's a good workaround indeed if you have few classes. 
One last question, though. What's the correct way of transforming prediction into mask images in a multiclass model?
At the momet I use a following chunk of code:

```
test_image = cv2.imread("test.jpg") / 255.
ready_image = np.expand_dims(test_image, axis=0)
prediction = model.predict(ready_image).round()
prediction = prediction.squeeze(axis=0)
masks = np.array_split(prediction, 4, axis=-1)
for i, mask in enumerate(masks):
    ready_mask = cv2.cvtColor(mask, cv2.COLOR_GRAY2RGB)
    ready_mask = ready_mask * 255
    cv2.imwrite(f"mask_{i}.jpg", ready_mask)
```
Results look messy, so I assume there's something wrong in my code.

**Comment by karolzak** [comment]
@EtagiBI the code you shared looks fine although I prefer array slicing to extract specific layers. Also GRAY2RGB conversion is unnecessary unless you really need it. Grayscale image is perfectly fine especially for segmentation mask.

If your prediction results look messy your model probably failed to learn anything.  
In my dummy example (training on a single image..) I used code below: 
```python
from keras_unet.models import custom_unet

model = custom_unet(
    (256,256,3), num_classes=3,
    use_batch_norm=False,
    dropout=0.0, dropout_type='standard',
    output_activation='sigmoid')

from tensorflow.keras.optimizers import Adam
from keras_unet.metrics import iou

model.compile(
    optimizer=Adam(),
    loss='binary_crossentropy',
    metrics=[iou]
)

model.fit(x, y, epochs=200)

```

When I tried building the network with `softmax` it couldn't learn anything.

**Comment by EtagiBI** [comment]
Thanks for your answers!
