### ISSUE TITLE
V-Net not working

### ISSUE THREAD

**Issue by kissievendor** [karolzak/keras-unet#29]
Hi, 
I think there might be something wrong with the v-net implementation.
When calling custom_unet (on its own) I get something like : 

<function keras_unet.models.custom_unet.custom_unet(input_shape,num_class ... ='sigmoid')>

When calling custom_vnet:

<module 'keras_unet.models.custom_vnet' ... custom_vnet.py'>

So the module rather than the function.

Best, Kirsten

**Comment by karolzak** [comment]
Hi @kissievendor 
Thanks for reporting this issue. I think this is related to init.py file under keras_unet/models.
![3FF33614-0152-40B5-9613-43A3EED7275F](https://user-images.githubusercontent.com/9843623/88088674-1582ae80-cb8b-11ea-8b2e-81d7aed0b1c0.jpeg)
It's missing an import statement for custom_vnet

**Comment by kissievendor** [comment]
Thanks! Could you push this fix to the package?
Otherwise I can't fix it in my container image.

**Comment by karolzak** [comment]
@kissievendor this should be now fixed from v0.1.2 going forward.
Thanks for your contribution!
