### ISSUE TITLE
Issue in multi-class- segmentation

### ISSUE THREAD

**Issue by ihamzariaz** [karolzak/keras-unet#31]
This is a great repo. Is your custom model suitable for multiple class segmentation.

**Comment by karolzak** [comment]
Hi @ihamzariaz - thanks!
Yes, the custom model is suitable for multi-class segmentation.
I covered this topic in depth in following issues:
https://github.com/karolzak/keras-unet/issues/25
https://github.com/karolzak/keras-unet/issues/4
https://github.com/karolzak/keras-unet/issues/3

Please look through those and in case you have any additional questions that were not covered before - don't hesitate to ask those :)
Cheers!
