### ISSUE TITLE
Including multiple classes in satellite unet

### ISSUE THREAD

**Issue by shubham-scisar** [karolzak/keras-unet#36]
I am finding this library very useful, it's really a great effort. I just wanted to know if I wish to get multiple classes in the predicted output, Will I have to give the masks having pixel values such as 0,1,2 each pixel value signifying separate class or is there any other way out ? I am just a beginner in unet for multi class segmentation ,so please help.

**Comment by karolzak** [comment]
Hi @shubhamsharma1609 , glad you're finding my repo useful.
In case of multi-class semantic segmentation problem your output will be a multilayered array with binary masks (layers) for each class.

I covered this topic in depth in following issues:
https://github.com/karolzak/keras-unet/issues/25
https://github.com/karolzak/keras-unet/issues/4
https://github.com/karolzak/keras-unet/issues/3

Please look through those and in case you have any additional questions that were not covered before - don't hesitate to ask those :)
Cheers!
