### ISSUE TITLE
Input 0 is incompatible with layer model

### ISSUE THREAD

**Issue by parcodepie** [karolzak/keras-unet#46]
I'm trying the default training (satellite unet) and train went good but when I'm trying to test the model I got the error 
`ValueError: Input 0 is incompatible with layer model: expected shape=(None, 384, 384, 3), found shape=(None, 348, 3)`

Here is my test code

```python
model_file = 'model_satellite.h5'
input_shape = (384, 384, 3)

model = satellite_unet(
    input_shape
)

model.load_weights(model_file)
image = np.array(Image.open("test.jpg").resize((348, 348)))
print("shape: ", image.shape)
shape:  (348, 348, 3)
pr_mask = model.predict(image).round()
```

**Comment by karolzak** [comment]
Hi @parcodepie 
Seems to me you made a mistake when resizing the test image. You used 348x348 instead of 384x384

**Comment by parcodepie** [comment]
Thanks @karolzak I edited it but it throws another error
`Input 0 is incompatible with layer model: expected shape=(None, 384, 384, 3), found shape=(32, 384, 3)`

**Comment by karolzak** [comment]
Your input array still have a wrong shape. It expects a batch of arrays of size 384x384x3 while you're providing 32 arrays of size 384x3. Something is wrong with your code

**Comment by parcodepie** [comment]
I'm trying to test only one image what could went wrong? 

here is the whole test code

```python
import cv2
import numpy as np
from keras_net.keras_unet.utils import get_patches
from keras_unet.models import satellite_unet
from PIL import Image

model_file = 'model_satellite.h5'
input_shape = (384, 384, 3)

model = satellite_unet(
    input_shape
)

model.load_weights(model_file)
image = np.array(Image.open("test.jpg").resize((384, 384)))
print("shape: ", image.shape)
shape:  (384, 384, 3)
pr_mask = model.predict(image).round()

cv2.imshow(
    "mask: ", pr_mask
)
```

**Comment by karolzak** [comment]
```python
image = np.array(Image.open("test.jpg").resize((384, 384)))
print("shape: ", image.shape)
shape: (384, 384, 3)
pr_mask = model.predict(image).round()
```

Ok, I see your problem. When providing inputs for prediction you need to serve images in batches - if you want to fit just a single image you need to reshape it from `(384, 384, 3)` to `(1, 384, 384, 3)`

**Comment by parcodepie** [comment]
Indeed it was the problem.
Here is the new working code
```python
image = np.array(Image.open("test.jpg").resize((384, 384)))
images_list = []
images_list.append(np.array(image))
x = np.asarray(images_list)
pr_mask = model.predict(x).round()

plt.imshow(
    pr_mask[0]
)
plt.show()
```

also I'm saving the image to the disk 
```python
data = Image.fromarray(np.reshape(pr_mask[0], (384, 384)) )
data = data.convert("L")
data.save('xxx.png')
```

the model needs more training but it's a good start

Thanks @karolzak  for your time

**Comment by gordonhu608** [comment]
> Thanks @karolzak I edited it but it throws another error
> `Input 0 is incompatible with layer model: expected shape=(None, 384, 384, 3), found shape=(32, 384, 3)`

Hi, so how did u fix the issue when you are testing many images instead of just one?

**Comment by hhhhhhhhhhhhhhhhho** [comment]
hi, i have a same problem ,too 

how fix that problem ?

Input 0 is incompatible with layer model: expected shape=(None, 64, 64, 3), found shape=(32, 64, 3) .. . .

**Comment by karolzak** [comment]
Hello @hhhhhhhhhhhhhhhhho ! Great username :)

As it was mentioned begore you need to serve images as an array. The solution mentioned above will work:
```python
image = np.array(Image.open("test.jpg").resize((384, 384)))
images_list = []
images_list.append(np.array(image))
x = np.asarray(images_list)
pr_mask = model.predict(x).round()

plt.imshow(
pr_mask[0]
)
plt.show()
```

**Comment by Anne-Andresen** [comment]
Had the same problem solved it by adding an additional dimension 
code before:
```python
for i in range(8):
    img = io.imread(TEST_PATH + str(i) + '.png')
    print('shape: ', img.shape)
    pred = model.predict(img)
    prediction = np.squeeze(pred) > .5
    plt.imsave(os.path.join(save_path, str(i) + '_predicted.png'), prediction)
```

Code after:
```python
for i in range(8):
    img = io.imread(TEST_PATH + str(i) + '.png')
    print('shape: ', img.shape)
    img = img[np.newaxis, :,  :, :]
    pred = model.predict(img)
    prediction = np.squeeze(pred) > .5
    plt.imsave(os.path.join(save_path, str(i) + '_predicted.png'), prediction)
```

**Comment by niranjanstudy06** [comment]
Hello @karolzak @Anne-Andresen , Can you please help me with the below problem.

I am currently trying to train a basic neural network with 3 different values from a dataset and predict another value. (Regression).

But I receive an input 0 incompatibility error. Kindly help.


Input NumPy array:
`
features.shape  #(1700, 3)
labels.shape #(1700, )
`

Neural Network
```
nn_model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu',input_shape = (1,3)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

nn_model.summary()
```

Summary:
<pre>
 dense_39 (Dense)            (None, 1, 64)             256       
                                                                 
 dense_40 (Dense)            (None, 1, 64)             4160      
                                                                 
 dense_41 (Dense)            (None, 1, 1)              65        
</pre>                                                                 
=================================================================
Total params: 4,481
Trainable params: 4,481
Non-trainable params: 0
_________________________________________________________________

<h3>Error:</h3>

```
history = nn_model.fit(
    features,
    labels,
    epochs=100,
    verbose=1,
)
```

`ValueError: Input 0 of layer "sequential_21" is incompatible with the layer: expected shape=(None, 1, 3), found shape=(None, 3)`

**Comment by karolzak** [comment]
@niranjanstudy06 the error message literally tells you what the problem is

try this instead:

```python
nn_model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu',input_shape = (3)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

```

**Comment by niranjanstudy06** [comment]
@karolzak what!?

This will obviously raise a type error problem...

**Comment by karolzak** [comment]
@niranjanstudy06 yeah, missed ',' there:
```python
input_shape = (3,)
```

**Comment by karolzak** [comment]
Also, this has nothing to do with `keras-unet`. Please go to stackoverflow with these kind of questions

**Comment by niranjanstudy06** [comment]
@karolzak Got it, sorry. I wasn't finding a solution there so I was trying to get help on github.

**Comment by niranjanstudy06** [comment]
@karolzak I deleted my comments on this, cause like you said they have nthg to do with unet. Kindly remove urs as well so that people won't get confused over it. Sorry for the inconvenience.

**Comment by tehreemnaqvi** [comment]
@karolzak I have the same error:

ValueError: Input 0 is incompatible with layer model: expected shape=(None, 9, 4), found shape=(9, 4).

This is my original data shape and I'm trying to generate synthetic data from TimeGAN. When I run the model, got the above error.

**Comment by karolzak** [comment]
@tehreemnaqvi Network is expecting batches of inputs of size (9,4). Please read through this thread. Your problem was already answered above.
