### ISSUE TITLE
 Input 0 of layer "sequential_1" is incompatible with the layer: expected shape=(None, 1, 3), found shape=(None, 3)

### ISSUE THREAD

**Issue by niranjanakella** [karolzak/keras-unet#51]
Hello @karolzak @Anne-Andresen , Can you please help me with the below problem.

I am currently trying to train a basic neural network with 3 different values from a dataset and predict another value. (Regression).

But I receive an input 0 incompatibility error. Kindly help.

Input NumPy array:
`
features.shape  #(1700, 3)
labels.shape #(1700, )
`

Neural Network
```
nn_model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu',input_shape = (1,3)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

nn_model.summary()
```

Summary:
<pre>
 dense_39 (Dense)            (None, 1, 64)             256       
                                                                 
 dense_40 (Dense)            (None, 1, 64)             4160      
                                                                 
 dense_41 (Dense)            (None, 1, 1)              65        
</pre>                                                                 
=================================================================
Total params: 4,481
Trainable params: 4,481
Non-trainable params: 0
_________________________________________________________________

<h3>Error:</h3>

```
history = nn_model.fit(
    features,
    labels,
    epochs=100,
    verbose=1,
)
```

`ValueError: Input 0 of layer "sequential_1" is incompatible with the layer: expected shape=(None, 1, 3), found shape=(None, 3)`

**Comment by karolzak** [comment]
Hey @niranjanstudy06, this is not even remotely related to `keras-unet` package. I propose you ask such question on more suitable platforms such as stackoverflow. Also, I answered your question here: https://github.com/karolzak/keras-unet/issues/46#issuecomment-966563899
